version: "3.9"
services:
  server:
    build: .
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DATABASE_CONNECTION_STRING=jdbc:postgresql://db:5432/rado
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rado0479
    depends_on:
      - db
    networks:
      - db_network
    restart: always

  db:
    container_name: postgresql-container
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "rado"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Rado0479"
    networks:
      - db_network
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

networks:
  db_network:
    driver: bridge